spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route pour Auth endpoints
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        # Route pour User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        # Route pour Inscription Service
        - id: inscription-service
          uri: lb://inscription-service
          predicates:
            - Path=/inscriptions/**

        # Route pour Campaign endpoints
        - id: campaign-service
          uri: lb://inscription-service
          predicates:
            - Path=/campaigns/**
          order: 1

        # Route pour Soutenance Service
        - id: soutenance-service
          uri: lb://soutenance-service
          predicates:
            - Path=/soutenances/**

        # Route pour Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        # Route pour Email Templates
        - id: template-service
          uri: lb://notification-service
          predicates:
            - Path=/templates/**

        # Route pour Admin Service
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

      # Découverte automatique des services
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
